source 'http://rubygems.org'

gem "middleman"

# Live-reloading plugin
gem "middleman-livereload"

gem 'haml'

gem 'bootstrap-sass', '~> 3.3.4'
gem 'sass-rails', '>= 3.2'
gem 'middleman-deploy', '~> 1.0'
gem 'font-awesome-sass', '~> 4.3.0'

